export const STORAGES_QUERY_KEYS = {
  users: ["users"] as const,
  groups: ["groups"] as const,
  policies: ["policies"] as const,
  accessKeys: ["access-keys"] as const,
  buckets: ["buckets"] as const,
  bucketSettings: (bucket: string) => ["bucket-settings", bucket] as const,
  objects: (bucket: string, prefix: string) => ["objects", bucket, prefix] as const,
  objectInfo: (bucket: string, key: string) => ["objects", bucket, "info", key] as const,
  objectTags: (bucket: string, key: string) => ["objects", bucket, "tags", key] as const,
  objectVersions: (bucket: string, key: string) => ["objects", bucket, "versions", key] as const,
  objectRetention: (bucket: string, key: string) => ["objects", bucket, "retention", key] as const,
  objectLegalHold: (bucket: string, key: string) => ["objects", bucket, "legal-hold", key] as const,
  lifecycle: (bucket: string) => ["lifecycle", bucket] as const,
  replication: (bucket: string) => ["replication", bucket] as const,
  events: (bucket: string) => ["events", bucket] as const,
  eventsTarget: ["events-target"] as const,
  tiers: ["tiers"] as const,
  kmsStatus: ["kms-status"] as const,
  kmsKeys: ["kms-keys"] as const,
  performance: ["performance"] as const,
  license: ["license"] as const,
  pools: ["pools"] as const,
};
