

/// A list of all valid configuration keys for a webhook target.
pub const NOTIFY_WEBHOOK_KEYS: &[&str] = &[
    crate::ENABLE_KEY,
    crate::WEBHOOK_ENDPOINT,
    crate::WEBHOOK_AUTH_TOKEN,
    crate::WEBHOOK_QUEUE_LIMIT,
    crate::WEBHOOK_QUEUE_DIR,
    crate::WEBHOOK_CLIENT_CERT,
    crate::WEBHOOK_CLIENT_KEY,
    crate::COMMENT_KEY,
];

// Webhook Environment Variables
pub const ENV_NOTIFY_WEBHOOK_ENABLE: &str = "NEUBULAFX_NOTIFY_WEBHOOK_ENABLE";
pub const ENV_NOTIFY_WEBHOOK_ENDPOINT: &str = "NEUBULAFX_NOTIFY_WEBHOOK_ENDPOINT";
pub const ENV_NOTIFY_WEBHOOK_AUTH_TOKEN: &str = "NEUBULAFX_NOTIFY_WEBHOOK_AUTH_TOKEN";
pub const ENV_NOTIFY_WEBHOOK_QUEUE_LIMIT: &str = "NEUBULAFX_NOTIFY_WEBHOOK_QUEUE_LIMIT";
pub const ENV_NOTIFY_WEBHOOK_QUEUE_DIR: &str = "NEUBULAFX_NOTIFY_WEBHOOK_QUEUE_DIR";
pub const ENV_NOTIFY_WEBHOOK_CLIENT_CERT: &str = "NEUBULAFX_NOTIFY_WEBHOOK_CLIENT_CERT";
pub const ENV_NOTIFY_WEBHOOK_CLIENT_KEY: &str = "NEUBULAFX_NOTIFY_WEBHOOK_CLIENT_KEY";

pub const ENV_NOTIFY_WEBHOOK_KEYS: &[&str; 7] = &[
    ENV_NOTIFY_WEBHOOK_ENABLE,
    ENV_NOTIFY_WEBHOOK_ENDPOINT,
    ENV_NOTIFY_WEBHOOK_AUTH_TOKEN,
    ENV_NOTIFY_WEBHOOK_QUEUE_LIMIT,
    ENV_NOTIFY_WEBHOOK_QUEUE_DIR,
    ENV_NOTIFY_WEBHOOK_CLIENT_CERT,
    ENV_NOTIFY_WEBHOOK_CLIENT_KEY,
];
